const translationEN = {
  welcomePage: {
    welcomeMessage: "Let everyone explore without limits.",
    welcomeLegend: "Versatile tool in terms of the volume and types of data it collects and manages and its ability to share information with other company systems.",
    Usuario: "User",
    about: "About",
    contact: "Contact",
    home: "Home"
  },
  blockloading: {
    "label.openapp": "Opening the app",
    "label.cargandoobjetos": "Loading Objects ",
    "label.of": " of "
  },
  filters: {
    "label.filtro.general": "General"
  },
  "AddData.Loading": "Loading...",
  "label.es" : 'Spanish',
  "label.en" : 'English',
  "Print.ChooseFormat": "Select type of file",
  "Print.Download": "Export",
  "Print.Failed.GenericMessage": "An error occurred during export. Please try again.",
  "Print.Failed.TimeoutMessage": "Export timed out. Please try again.",
  "Print.Image.CompletedLink": "Click here to download your image file.",
  "Print.Image.CurrentSize": "Current",
  "Print.Image.Dpi": "Resolution (dots per inch)",
  "Print.Image.Format": "Type of file",
  "Print.Image.Height": "Height (pixels)",
  "Print.Image.Title": "Image settings",
  "Print.Image.Width": "Width (pixels)",
  "Print.Image.Custom": "Custom",
  "Print.Landscape": "Landscape",
  "Print.Layout": "Orientation",
  "Print.Layout.Aspect": "Aspect ratio options",
  "Print.Layout.BestFitNoPreserveAspectRatio": "Fit to page",
  "Print.Layout.BestFitPreserveAspectRatio": "Fit to page, keep aspect ratio",
  "Print.Layout.CurrentSize": "Keep current size",
  "Print.PaperSize": "Paper size",
  "Print.PaperSize.Letter": "Letter",
  "Print.Pdf.CompletedLink": "Click here to download your PDF file.",
  "Print.Pdf.Title": "PDF settings",
  "Print.Portrait": "Portrait",
  "Print.Ppt.CompletedLink": "Click here to download your PowerPoint presentation.",
  "Print.Ppt.Format": "Slide size",
  "Print.Ppt.Format.Custom": "Custom",
  "Print.Ppt.Format.Standard": "Standard",
  "Print.Ppt.Format.Widescreen": "Widescreen",
  "Print.Ppt.Title": "PowerPoint settings",
  "Export.Completed": "Full export",
  "Export.CompletedDescription": "Your exported data is ready for download.",
  "Export.CompletedLink": "Click here to download your data file.",
  "filters.label.selecciones": "Selections",
  "filters.label.nofiltros": "No filters selected",
  "filters.label.todos": "Select all",
  "filters.label.alternativos": "Select alternative",
  "filters.label.excluidos": "Select excluded",
  "filters.label.desbloquear": "Click to unlock",
  "filters.label.bloquear": "Click to lock",
  "filters.label.borrar": "Clear selection",
  "filters.label.limpiarselecciones": "Clear selections",
  "bookmark.aplicarmarcadores": "Apply bookmark",
  "bookmark.StartBookmarkHint": "This bookmark will be applied when you open the app.",
  "bookmark.descripcion": "Description",
  "bookmark.selecciones": "Selections",
  "bookmark.fechaCreacion": "Creation date",
  "bookmark.title.StartBookmark": "This bookmark will be applied when opening the app.",
  "bookmark.label.StartBookmark": "Default",
  "bookmark.label.StartBookmarkUser": "Default by user",
  "bookmark.publicarmarcador": "Make bookmark public",
  "bookmark.despublicarmarcador": "Make bookmark private",
  "bookmark.editarmarcadores": "Edit bookmark",
  "bookmark.eliminaraBookmar": "The bookmark will be deleted.",
  "bookmark.accionnoback": "This action can not be undone. Do you wish to continue?",
  "bookmark.bookmarkEliminado": "The marker has been removed",
  "bookmark.bookmarkEliminadoError": "Could not delete bookmark.",
  "bookmark.newbookmark": "Create new bookmark",
  "bookmark.modal.titulo": "Title",
  "bookmark.modal.descripcion": "Description",
  "bookmark.modal.opcional": "(Optional)",
  "bookmark.modal.hoja": "Save sheet location",
  "bookmark.modal.guardarByUser": "Save bookmark as default",
  "bookmark.KObookmark": "You must enter the name of the bookmark",
  "bookmark.Bookmarkexiste": "A bookmark with this title already exists. Assign another title to the bookmark.",
  "bookmark.OKbookmark": "The bookmark has been created",
  "bookmark.ErrorCreatingBookmark": "An error occurred while creating the bookmark. Please try again later.",
  "bookmark.BookmarkByUserExist": `<strong>A predefined Bookmark already exists.</strong> <br> Do you want to update?`,
  "bookmark.OKbookmarkUpdate": "The bookmark has been updated",
  "bookmark.UpdateUbicacion": "Update sheet location",
  "bookmark.OKpublishBookmark": "The bookmark has been published",
  "bookmark.OKunPublishBookmark": "The bookmark has been unpublished",
  "bookmark.KOpublishBookmark": "The bookmark could not be published",
  "bookmark.KOunpublishBookmark": "The bookmark could not be unpublished",
  "Bookmarks.BookmarkActive": "Active bookmark",
  "Bookmarks.NoBookmarkActive": "There is no Bookmark selected",
  "glosario.glosario": "Glossary",
  "glosario.DimensionesMedidas": "Dimensions and Measurements",
  "glosario.dimensiones": "Dimensions",
  "glosario.medidas": "Measures",
  "favoritos.favoritos": "Favorites",
  "favoritos.create.date": "Added",
  "favoritos.deletefavorite": "Remove from favorites",
  "favoritos.addFavorites": "Add to favorites",
  "favoritos.gotopage": "Go to the page where the object is located",
  "favoritos.alert.addToFavorites": "Item added to favorites",
  "favoritos.alert.deleteToFavorites": "Item removed from favorites",
  "favoritos.alert.errorAddToFavorites": "Error adding to favorites",
  "favoritos.alert.errorDeleteToFavorites": "Failed to delete favorite",
  "Favorites.Welcome": `<h3>Welcome to your favorites section.</h3><p>Currently, you have no items in your favorites list. To add your preferred visualizations to this section, click on the corresponding button on each object, report, or chart and select the "Add to favorites" option.</p><p>You can remove items from your favorites list at any time by clicking on the <i className="ri-delete-bin-line"></i> icon.</p>`,
  "visualizaciones.visualizaciones": "Views",
  "visualizaciones.modo.objeto": "Object view mode",
  "visualizaciones.modo.lista": "List view mode",
  "visualizaciones.fechaCreacion": "Creation date",
  "visualizaciones.fechaModificacion": "Modification date",
  'visualizaciones.appname': "Section",
  'visualizaciones.usuario': "User",
  "visualizaciones.publicarvisualizacion": "Make the visualization public.",
  "visualizaciones.despublicarvisualizacion": "Make the visualization private",
  "visualizaciones.vervisualizacion": "See visualization",
  "visualizaciones.modal.eliminarVisualizacion": "The object will be deleted.",
  "visualizaciones.modal.accionnoback": "This action can not be undone. Do you wish to continue?",
  "visualizaciones.acciones.eliminadovisualizacion": "Visualization has been removed",
  "visualizaciones.noresultados": "You don't have any custom visualization yet.",
  "visualizaciones.publicOk": "The visualization was published successfully.",
  "visualizaciones.publicKo": "The visualization was not published correctly.",
  "visualizaciones.unpublicOk": "The visualization has been successfully unpublished.",
  "visualizaciones.unpublicKo": "The visualization has not been unpublished correctly.",
  "visualizaciones.placeholder.buscarvisualizaciones": "Search visualizations...",
  "GlobalSelections.CurrentSelections": "Selections",
  "GlobalSelections.CurrentSelections.Default": "Selections (in default state)",
  "GlobalSelections.AppDimensions": "App dimensions",
  "GlobalSelections.DimensionsWarning": "Only dimensions present in Master items are displayed",
  "GlobalSelections.NoMatchesForSearch": "There are no matches.",
  "GlobalSelections.ShowFields": "Show fields",
  "GlobalSelections.HideFields": "Hide fields",
  "GlobalSelections.FilterDimensions": "Search dimensions",
  "GlobalSelections.FilterDimensionsAndFields": "Search dimensions and fields",
  "GlobalSelections.NoSelections": "No selections applied",
  "GlobalSelections.NoSelectionsBody": "Apply selections from the fields below to explore the associations in your data. The selections that you make in the sheet are also displayed here.",
  "compare.nameEstadoTxtInicial": 'Initial state',
  "compare.label.estadoInicial": "Return graph to its initial state",
  "compareobject.btn.messageopen": 'Select what you want to compare with..',
  "compareobject.btn.sameobject": 'Same graphic',
  "compareobject.btn.listobject": 'Choose from list',
  "compare.btn.newstate": 'New state',
  "compare.btn.listastaters": 'States list',
  "compare.btn.exportpdf": 'Export to PDF',
  "compare.tooltips.close": 'Close the window deleting the created states',
  "compareobject.btn.hideFilterSection": "Hide filters",
  "compareobject.btn.showFilterSection": "Show filters",
  "compare.label.filtersMensaje": "Apply selections from the fields below to explore the associations in your data.",
  "compare.tooltips.createsatate": 'Create a new state.',
  "compare.tooltips.openliststates": 'Open list of created states',
  "compare.tooltips.sameobject": 'Choose the initial graph to compare it with itself',
  "compare.tooltips.listobject": 'Choose a chart from the list to compare it',
  "compare.modal.headermodal": 'Create new state',
  "compare.modal.labeltitle": 'State title',
  "compare.modal.mensajepdf": 'Downloading PDF',
  "compare.acciones.KOState": "You must enter the name of the state",
  "compare.acciones.CrearState": "The state has been created",
  "compare.acciones.DeleteState": "The state has been removed",
  "compare.acciones.EliminarState": "Status has been removed",
  "compare.acciones.Stateexiste": "There is already a state with this name. Give the state another name.",
  "compare.acciones.fullsize": "Full size",
  "compare.acciones.normalsize": "Full size exit",
  "compare.acciones.vistaColumna": "Column view",
  "compare.acciones.vistaRow": "Row View",
  "compare.pdf.Objeto_1": "Generating main object image",
  "compare.pdf.Objeto_2": "Generating secondary object image",
  "compare.pdf.selecciones_1": "Generating main object selections",
  "compare.pdf.selecciones_2": "Generating child object selections",
  "compare.pdf.imgCoorporativa": "Obtaining corporate image",
  "compare.pdf.title": "Graphics comparison",
  "compare.pdf.objetoPrincipal": "Main graph",
  "compare.pdf.objetoSecundario": "Selected graph",
  "compare.tooltips.estadoInicial": "Return graph to its initial state",
  'compare.tooltips.reloadObject': "Reload the chart",
  "compare.tooltips.exportimagen": "Export as an image",
  "compare.tooltips.exportdatos": "Export data",
  "compare.tooltips.addFilter": "Add selection to chart",
  "compare.tooltips.verGrafico": "View chart",
  "compare.tooltips.verDatos": "View data",
  "compare.pdf.selecciones": "Selections",
  "compare.pdf.addtitle": "PDF Title",
  "compare.pdf.askForTitle": "Please enter a title for your report.",
  "compare.pdf.txtCaracter": "characters",
  "compare.object.error": "Sorry, an unexpected error occurred. Please try again later. If the issue persists, feel free to contact our support team for help. Sorry for the disturbances.",
  "compare.AlternateState.NewStateName": "New state name",
  "sheets.modal.title": "Custom Sheet Information",
  "sheets.modal.SI": "YES",
  "sheets.modal.NO": "NO",
  "sheets.menu.sheet": "Custom sheets",
  "sheets.openapp": "Open app",
  "sheets.infoSheet": "Show info",
  "sheets.closeInfoSheet": "Close info",
  "order.menu.nombreHoja": "Sheet Name",
  "order.menu.publicado": "Published",
  "order.menu.aprovado": "Approved",
  "order.menu.fechacreacion": "Creation date",
  "order.menu.fechapublicacion": "Publish time",
  "order.menu.fechamodificacion": "Modified Date",
  "order.menu.propietario": "Owner",
  "equalizer.label.datos": 'Data',
  "equalizer.label.ordenar": 'Sorting',
  "equalizer.label.presentacion": 'Presentation',
  "equalizer.label.colores": 'Colors and legend',
  "equalizer.label.cabecerasyetiquetas": 'Headers and labels',
  "equalizer.label.cabecera": 'Headers ',
  "equalizer.label.superponeretiquetas": 'Overlay labels',
  "equalizer.label.etiquetashojas": 'Leaf labels',
  "equalizer.label.etiquetasvalores": 'Value labels',
  "equalizer.label.titulos": 'Titles',
  "equalizer.label.dimensiones": 'Dimensions',
  "equalizer.label.medidas": 'Measures',
  "equalizer.label.campos": 'Fields',
  "equalizer.label.ascendente": 'Ascending',
  "equalizer.label.descendente": 'Descending',
  "equalizer.label.valoresextremos": 'Include outliers',
  "equalizer.label.vertical": 'Vertical',
  "equalizer.label.horizontal": 'Horizontal',
  "equalizer.label.agrupado": 'Grouped',
  "equalizer.label.apilado": 'Stacked',
  "equalizer.label.valoresperdidos": 'Missing values',
  "equalizer.label.mostrarhuecos": 'Show as gaps',
  "equalizer.label.mostrarconexiones": 'Show as connections',
  "equalizer.label.mostrarceros": 'Show as zeros',
  "equalizer.label.mostrarpuntos": 'Show data points',
  "equalizer.label.tamanioburbuja": 'Bubble size',
  "equalizer.label.reolucioncompresion": 'Compression resolution',
  "equalizer.label.puntosfluctuacion": 'Jitter points',
  "equalizer.label.activado": 'On',
  "equalizer.label.desactivado": 'Off',
  "equalizer.label.personalizado": 'Custom',
  "equalizer.label.colorunico": 'Single color',
  "equalizer.label.porDimension": 'By dimension',
  "equalizer.label.porMedida": 'By measure',
  "equalizer.label.multicolor": 'Multicolored',
  "equalizer.label.porExpresion": 'By Expression',
  "equalizer.label.esquemacolor": 'Color scheme',
  "equalizer.label.mostrarleyenda": 'Show legend',
  "equalizer.label.mostrarleyendaTitulo": 'Show legend title',
  "equalizer.label.mostrartitulo": 'Show titles',
  "equalizer.label.mostraretiqueta": 'Show label',
  "equalizer.label.titulo": 'Title',
  "equalizer.label.subtitulo": 'Subtitle',
  "equalizer.label.piepagina": 'Footnote',
  "equalizer.label.posicionleyenda": 'Legend position',
  "equalizer.label.posicion": 'Position',
  "equalizer.label.automatico": 'Auto',
  "equalizer.label.derecha": 'Right',
  "equalizer.label.final": 'Bottom',
  "equalizer.label.izquierda": 'Left',
  "equalizer.label.principio": 'Top',
  "equalizer.label.etiquetavalores": 'Value labels',
  "equalizer.label.capas": 'Layers',
  "equalizer.label.configuracionmapa": 'Map settings',
  "equalizer.label.idiomamapa": 'Map language',
  "equalizer.label.capa.puntos": 'Point layer',
  "equalizer.label.capa.grafico": 'Chart layer',
  "equalizer.label.capa.lineas": 'Line layer',
  "equalizer.label.capa.densidad": 'Density layer',
  "equalizer.label.capa.area": 'Area layer',
  "equalizer.label.capa.fondo": 'Background layer',
  "equalizer.label.mapabase": 'Base map',
  "equalizer.label.prederminado": 'Default',
  "equalizer.label.palido": 'Pale',
  "equalizer.label.satelite": 'Satellite',
  "equalizer.label.ninguna": 'None',
  "equalizer.label.todos": 'All',
  "equalizer.label.cuota": 'Share',
  "equalizer.label.valores": 'Values',
  "equalizer.label.ingles": 'English',
  "equalizer.label.local": 'Local',
  "equalizer.label.zoomauto": 'Auto-zoom',
  "equalizer.label.mostrarcapa": 'Show layer',
  "equalizer.label.rangoburbuja": 'Bubble size range',
  "equalizer.label.rangotriangulo": 'Triangle size range',
  "equalizer.label.rangocuadrado": 'Square size range',
  "equalizer.label.rangopentagono": 'Pentagon size range',
  "equalizer.label.rangohexagono": 'Hexagon size range',
  "equalizer.label.rangotarta": 'Pie chart size',
  "equalizer.label.rangolinea": 'Line width',
  "equalizer.label.radioinfluencia": 'Influence radiux',
  "equalizer.label.alto": 'Height',
  "equalizer.label.ancho": 'Width',
  "equalizer.label.navegacion": 'Navigation',
  "equalizer.label.etiquetas": 'Labels',
  "equalizer.label.linea": 'Line',
  "equalizer.label.area": 'Area',
  "equalizer.label.escalalogaritmica": 'Logarithmic scale',
  "equalizer.label.tarta": 'Pie',
  "equalizer.label.donut": 'Donut',
  "equalizer.label.colorespersistentes": 'Persistent colors',
  "equalizer.label.expandirtodo": 'Expand all',
  "equalizer.label.contraertodo": 'Collapse all',
  "equalizer.label.tablatotales": 'Totals',
  "equalizer.label.desplazamiento": 'Scrolling',
  "equalizer.label.inmovilizarColumna": 'Freeze first column',
  "equalizer.label.desHorizontal": 'Horizontal scrolling',
  "equalizer.label.ajustesTexto": 'Multiline text wrapping',
  "equalizer.label.textoCabecera": 'Wrap text in headers',
  "equalizer.label.textoCelda": 'Wrap text in cells',
  "equalizer.label.filtros": "Filters",
  "equalizer.label.stylesline": "Line styles",
  "equalizer.btn.guardar": 'Save',
  "equalizer.btn.aplicar": 'Apply',
  "equalizer.btn.cancelar": 'Cancel',
  "equalizer.btn.cerrar": 'Close',
  "equalizer.btn.descartar": 'Discard',
  "equalizer.title.mover": 'Move',
  "equalizer.title.ascendente": 'Ascending',
  "equalizer.title.descendente": 'Descending',
  "equalizer.title.vertical": 'Vertical',
  "equalizer.title.horizontal": 'Horizontal',
  "equalizer.modal.atencion": 'Attention',
  "equalizer.modal.aviso": 'Changes have not been saved.',
  "equalizer.modal.avisoClose": 'Discard changes.',
  "equalizer.modal.cambios": 'Apply the changes?',
  "equalizer.modal.cambiosexplicacion": 'All changes will be applied to the properties of the object.',
  "equalizer.modal.errormensaje": 'Selection has created an inconsistency.',
  "equalizer.language.spaniol": 'Spanish',
  "equalizer.language.ingles": 'English',
  "equalizer.language.frances": 'French',
  "equalizer.geo.properties.showDebugInfo": "Debug info",
  "Object.PieChart": "Pie chart",
  "Object.BarChart": "Bar chart",

  "treepermissions.titles.roles": "Roles",
  "treepermissions.titles.perfiles": "Profiles",
  "treepermissions.titles.groups": "Groups",
  "treepermissions.titles.users": "Users",
  "treepermissions.titles.functionality": "Functionality",
  "treepermissions.titles.identification": "Identification",
  "treepermissions.titles.rulesapplied": "Rules applied",
  "treepermissions.actions.selectall": "select all",
  "treepermissions.actions.newuser": "new user",
  "treepermissions.actions.newgroup": "new group",
  "treepermissions.actions.newrole": "new role",
  "treepermissions.actions.newprofile": "new profile",
  "treepermissions.placeholder.search": "search...",
  "treepermissions.buttons.new": "New",
  "treepermissions.buttons.new.role": "Role",
  "treepermissions.buttons.new.profile": "Profile",
  "treepermissions.buttons.new.group": "Group",
  "treepermissions.buttons.new.user": "User",
  "treepermissions.buttons.assign": "Assign",
  "treepermissions.buttons.delete": "Delete",
  "treepermissions.buttons.rules": "Rules",
  "treepermissions.buttons.save": "Save",
  "treepermissions.buttons.add": "Add",
  "treepermissions.buttons.accept": "Accept",
  "treepermissions.buttons.cancel": "Cancel",
  "treepermissions.buttons.close": "Close",
  "treepermissions.buttons.replace": "Replace",
  "treepermissions.buttons.edit": "Edit",
  "treepermissions.buttons.expandall": "Expand All",
  "treepermissions.buttons.collapseall": "Collapse All",
  "treepermissions.rules.empty": "There are no rules to show",
  "treepermissions.legend.allowed": "Allowed",
  "treepermissions.legend.blocked": "Blocked",
  "treepermissions.legend.indeterminate": "Indeterminate",
  "treepermissions.legend.blank": "Blank",
  "treepermissions.modals.userform.user": "User",
  "treepermissions.modals.userform.firstname": "First Name",
  "treepermissions.modals.userform.lastname": "Last Name",
  "treepermissions.modals.userform.domain": "Domain",
  "treepermissions.modals.userform.gender": "Gender",
  "treepermissions.modals.userform.email": "e-Mail",
  "treepermissions.modals.userform.address": "Address",
  "treepermissions.modals.userform.phone": "Phone",
  "treepermissions.modals.userform.role": "Role",
  "treepermissions.modals.userform.birthday": "Birthday",
  "treepermissions.modals.delete.title": "Do you want to delete the selections?",
  "treepermissions.modals.assign.title": "Assign Groups",
  "treepermissions.modals.assign.body": "Do you want to add or replace the selected groups?",
  "treepermissions.modals.assign.role.title": "Assign Role",
  "treepermissions.modals.assign.role.body": "Do you want to replace the selected role?",
  "treepermissions.modals.assign.profile.title": "Assign Profile",
  "treepermissions.modals.assign.profile.body": "Do you want to replace the selected profile?",
  "treepermissions.modals.delete.rule.title": "Delete rule",
  "treepermissions.modals.delete.rule.body": "Do you want to delete the rule '{{rule}}'?",
  "treepermissions.modals.save.label": "Save options",
  "treepermissions.modals.save.title": "What do you want to save?",
  "treepermissions.modals.save.section1": "Options",
  "treepermissions.modals.save.section1.opt1": "Add permissions to users",
  "treepermissions.modals.save.section1.opt1small": "Permissions will be added to users without deleting the ones already created.",
  "treepermissions.modals.save.section1.opt2": "Replace selected permissions",
  "treepermissions.modals.save.section1.opt2small": "Old permissions will be erased and replaced by selected ones.",
  "treepermissions.modals.save.section1.opt3": "Create a permission rule",
  "treepermissions.modals.save.section1.opt3small": "A rule will be created that applies the permissions to the selection. It is necessary to have selected a role or group.",
  "treepermissions.modals.save.section2": "Selections",
  "treepermissions.modals.save.section2.opt1": "Only apply to selected users",
  "treepermissions.modals.save.section2.opt2": "Apply to selected and related users",
  "treepermissions.modals.save.section3": "Rule Name",
  "treepermissions.modals.save.section3.replace": "The rule already exists, do you want to replace it?",
  "treepermissions.modals.save.section3.required": "A rule name is required",
  "treepermissions.modals.save.section3.placeholder": "Write a rule name...",
  "treepermissions.toast.permissionsload": 'Permissions loaded successfully!',
  "treepermissions.toast.roleupdate": "Role successfully updated",
  "treepermissions.toast.rolecreate": "Role successfully created",
  "treepermissions.toast.profileupdate": "Profile successfully updated",
  "treepermissions.toast.profilecreate": "Profile successfully created",
  "treepermissions.toast.groupupdate": "Group successfully updated",
  "treepermissions.toast.groupcreate": "Group successfully created",
  "treepermissions.toast.roledelete": "Role '{{role}}' successfully removed",
  "treepermissions.toast.profiledelete": "Profile '{{role}}' successfully removed",
  "treepermissions.toast.groupdelete": "Group '{{group}}' successfully removed",
  "treepermissions.toast.userdelete": "User '{{user}}' successfully removed",
  "treepermissions.toast.deleteselerror": "It is necessary to select at least one user, one role or one group",
  "treepermissions.toast.deleteselerrorperfil": "It is necessary to select at least one user, one profile or one group",
  "treepermissions.toast.assignselerror01": "It is necessary to select at least one user and one role or group",
  "treepermissions.toast.assignselerror01perfil": "It is necessary to select at least one user and one profile or group",
  "treepermissions.toast.assignselerror02": "Only one role per user is allowed",
  "treepermissions.toast.assignselerror02perfil": "Only one profile per user is allowed",
  "treepermissions.toast.assignselsuccess01": "Group and roles have been added successfully",
  "treepermissions.toast.assignselsuccess01perfil": "Group and profiles have been added successfully",
  "treepermissions.toast.assignselsuccess02": "Group and roles have been successfully replaced",
  "treepermissions.toast.assignselsuccess02perfil": "Group and profiles have been successfully replaced",
  "treepermissions.toast.assignselsuccess03": "Rol have been successfully replaced",
  "treepermissions.toast.assignselsuccess03perfil": "Profile have been successfully replaced",
  "treepermissions.toast.savedialogsuccesscreated": "User successfully created",
  "treepermissions.toast.savedialogsuccessupdated": "User successfully updated",
  "treepermissions.toast.savedialogerror": "At least one functionality needs to be selected",
  "treepermissions.toast.rulecreate": "Rule '{{rule}}' created succesfully",
  "treepermissions.toast.permissionscreate": "Permissions created succesfully",
  "treepermissions.toast.ruledelete": "Rule '{{rule}}' successfully removed",
  "treepermissions.toast.sequelizeerrorforeignkey": "Error, the record is being referenced in another table",
  "views.label.preferencias": "Preferences",
  "views.label.marcadores": "Bookmark",
  "views.label.glosario": "Glossary",
  "views.label.filtros": "Filters",
  "views.label.temas": "Themes",
  "views.label.opciones": "Options",
  "views.label.videos": "Videos",
  "views.label.loadvideos": "Looking for help videos....",
  "views.label.novideos": "There are currently no help videos uploaded.",
  "views.search.Placeholder": "Search",
  contextMenu: {
    "label.volver": "Back",
    "label.PantallaCompleta": "Full screen",
    "label.SalirPantallaCompleta": "Exit full screen",
    "label.verGrafico": "View chart",
    "label.verDatos": "View data",
    "label.descargarComo": "Download as",
    "label.exportImagen": "Image",
    "label.exportPdf": "PDF",
    "label.exportDatos": "Data",
    "label.softPatches": 'Return initial state',
    "label.expand": "Expand/Collapse",
    "label.expandirtodo": 'Expand all',
    "label.contraertodo": 'Collapse all',
    "label.copyToClipboard": 'Copy cell value',
    "label.compararObjetos": 'Comparative',
    "label.menuexploracion": 'Open exploration menu',
    "label.compartir": 'Share',
  },
  common: {
    "label.esperar": "Please wait.",
    "Common.Aceptar": "Ok",
    "Common.Cancel": "Cancel",
    "Common.Eliminar": "Delete",
    "Common.Atencion": "Atención",
    "Common.Buscar": "Search for",
    "Common.Cerrar": "Close",
    "Common.Copy": "Copiar",
    "ObjectNotFound": "The object could not be loaded.</br>Consult the supplier.",
    "Common.LastReloadTime": "Last update",
    "Common.logoutconfirm" : "Are you sure to log out?",
    inicio: "Home",
    about: "About",
    contact: "Contact",
    home: "Home"
  },
  menu: {
    inicio: "Home",
    ventas: "Sales",
    financiero: "Financial",
    favoritos: "Favorites",
    visualizaciones: "Visualizations",
    permisos: "Permissions",
    analisis: "Analysis",
    distribucion: "Distribution",
    evolucionIndicadores: "Evolution of Indicators",
    indicadores: "Indicators",
    resumen: "Summary",
    sheet: "Custom sheets",
  },
  sheetCreation: {
    "title": "Create a new sheet",
    "intro": "Custom sheets are created from the Qlik Sense application. You can open the Qlik Sense application connected to this module by clicking the button",
    "buttonText": "OPEN_APPLICATION",
    "instructions": "Once you have opened the application, do the following:",
    "step1": "From the app overview, click the icon to view the sheets.",
    "step2": "Click the icon to create a new sheet or on Create new sheet.",
    "step3": {
      "title": "Assign a title to the sheet using the following format:",
      "part1": "Start with the defined prefix",
      "part2": "Add the module to which the sheet belongs, ending with a period. The module names are (each is a different application):",
      "part3": "End the sheet title with the name you want the custom sheet to display."
    },
    "step4": "Add a description.",
    "step5": "Click outside the text area to save the title and description.",
    "example": "Example:",
    "createdSheet": "A new sheet has been created. Your sheets are private until you make them public.",
    "makePublicInfo": "For more information, see <a href='https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Share/make-public-or-private.htm' target='_blank'>Grant access to sheets, bookmarks, and stories.</a>",
    "refreshInfo": "To view the newly created sheet, you must refresh the page in the browser.",
    "buttonOpenApp": "Open application"
  }
};
export default translationEN;
