const translationES = {
  welcomePage: {
    welcomeMessage: "Permita que todo el mundo explore sin límites.",
    welcomeLegend: "Herramienta versátil en cuanto al volumen y tipos de datos que recopila y gestiona y su capacidad para compartir información con otros sistemas de la empresa.",
    Usuario: "Usuario",
    about: "About",
    contact: "Contact",
    home: "Home"
  },
  blockloading: {
    "label.openapp": "Abriendo la aplicación",
    "label.cargandoobjetos": "Cargando Objetos ",
    "label.of": " de "
  },
  filters: {
    "label.filtro.general": "General"
  },
  "AddData.Loading": "Cargando...",
  "label.es" : 'Español',
  "label.en" : 'Inglés',
  "Print.ChooseFormat": "Seleccionar tipo de archivo",
  "Print.Download": "Exportar",
  "Print.Failed.GenericMessage": "Se ha producido un error en la exportación. Por favor, inténtelo de nuevo.",
  "Print.Failed.TimeoutMessage": "El tiempo de exportación ha expirado. Por favor, inténtelo de nuevo.",
  "Print.Image.CompletedLink": "Haga clic aquí para descargar su archivo de imagen.",
  "Print.Image.CurrentSize": "Actual",
  "Print.Image.Dpi": "Resolución (puntos por pulgada)",
  "Print.Image.Format": "Tipo de archivo",
  "Print.Image.Height": "Alto (píxeles)",
  "Print.Image.Title": "Configuraciones de imagen",
  "Print.Image.Width": "Ancho (píxeles)",
  "Print.Image.Custom": "Personalizado",
  "Print.Landscape": "Apaisado",
  "Print.Layout": "Orientación",
  "Print.Layout.Aspect": "Opciones de ratio de aspecto",
  "Print.Layout.BestFitNoPreserveAspectRatio": "Ajustar a la página",
  "Print.Layout.BestFitPreserveAspectRatio": "Ajustar a la página, mantener ratio de aspecto",
  "Print.Layout.CurrentSize": "Mantener tamaño actual",
  "Print.PaperSize": "Tamaño de papel",
  "Print.PaperSize.Letter": "Carta",
  "Print.Pdf.CompletedLink": "Haga clic aquí para descargar su archivo PDF.",
  "Print.Pdf.Title": "Configuraciones de PDF",
  "Print.Portrait": "Vertical",
  "Print.Ppt.CompletedLink": "Haga clic aquí para descargar su presentación de PowerPoint.",
  "Print.Ppt.Format": "Tamaño de diapositiva",
  "Print.Ppt.Format.Custom": "Personalizado",
  "Print.Ppt.Format.Standard": "Estándar",
  "Print.Ppt.Format.Widescreen": "Pantalla panorámica",
  "Print.Ppt.Title": "Configuraciones de PowerPoint",
  "Export.Completed": "Exportación completa",
  "Export.CompletedDescription": "Sus datos exportados están listos para descargarse.",
  "Export.CompletedLink": "Haga clic aquí para descargar su archivo de datos.",
  "filters.label.selecciones": "Selecciones",
  "filters.label.nofiltros": "No hay filtros seleccionados",
  "filters.label.todos": "Seleccionar todo",
  "filters.label.alternativos": "Seleccionar alternativos",
  "filters.label.excluidos": "Seleccionar excluidos",
  "filters.label.desbloquear": "Haga clic para desbloquearla",
  "filters.label.bloquear": "Haga clic para bloquearla",
  "filters.label.borrar": "Borrar selección",
  "filters.label.limpiarselecciones": "Limpiar selecciones",
  "bookmark.aplicarmarcadores": "Aplicar marcador",
  "bookmark.StartBookmarkHint": "Este marcador se aplicará al abrir la app.",
  "bookmark.descripcion": "Descripción",
  "bookmark.selecciones": "Selecciones",
  "bookmark.fechaCreacion": "Fecha creación",
  "bookmark.title.StartBookmark": "Este marcador se aplicará al abrir la app.",
  "bookmark.label.StartBookmark": "Predeterminado",
  "bookmark.label.StartBookmarkUser": "Predeterminado por usuario",
  "bookmark.publicarmarcador": "Hacer público el marcador",
  "bookmark.despublicarmarcador": "Hacer privado el marcador",
  "bookmark.editarmarcadores": "Editar marcador",
  "bookmark.eliminaraBookmar": "Se eliminará el marcador.",
  "bookmark.accionnoback": "Esta acción no se puede deshacer. Desea continuar?",
  "bookmark.bookmarkEliminado": "Se ha eliminado el marcador",
  "bookmark.bookmarkEliminadoError": "No se ha podido eliminar el marcador.",
  "bookmark.newbookmark": "Crear nuevo marcador",
  "bookmark.modal.titulo": "Título",
  "bookmark.modal.descripcion": "Descripción",
  "bookmark.modal.opcional": "(Opcional)",
  "bookmark.modal.hoja": "Guardar ubicación de hoja",
  "bookmark.modal.guardarByUser": "Guardar marcador como predefino",
  "bookmark.KObookmark": "Debe introducir el nombre del marcador",
  "bookmark.Bookmarkexiste": "Ya existe un marcador con este título. Asigne otro título al marcador.",
  "bookmark.OKbookmark": "Se ha creado el marcador",
  "bookmark.ErrorCreatingBookmark": "Se produjo un error al crear el marcador. Por favor, inténtalo de nuevo más tarde.",
  "bookmark.BookmarkByUserExist": `<strong>Ya existe un Bookmark predefinido.</strong> <br> Quieres actualizar?`,
  "bookmark.OKbookmarkUpdate": "El marcador se ha actualizado",
  "bookmark.UpdateUbicacion": "Actualizar ubicación de la hoja",
  "bookmark.OKpublishBookmark": "El marcador ha sido publicado.",
  "bookmark.OKunPublishBookmark": "El marcador ha sido despublicado.",
  "bookmark.KOpublishBookmark": "No se pudo publicar el marcador.",
  "bookmark.KOunpublishBookmark": "El marcador no se pudo despublicar",
  "Bookmarks.BookmarkActive": "Bookmark activo",
  "Bookmarks.NoBookmarkActive": "No hay ningun Bookmark seleccionado",
  "glosario.glosario": "Glosario",
  "glosario.DimensionesMedidas": "Dimensiones y Medidas",
  "glosario.dimensiones": "Dimensiones",
  "glosario.medidas": "Medidas",
  "favoritos.favoritos": "Favoritos",
  "favoritos.create.date": "Añadido",
  "favoritos.deletefavorite": "Eliminar de favoritos",
  "favoritos.addFavorites": "Agregar a favoritos",
  "favoritos.gotopage": "Ir a la página donde se encuentra el objeto",
  "favoritos.alert.addToFavorites": "Elemento añadido a favoritos",
  "favoritos.alert.deleteToFavorites": "Elemento eliminado de favoritos",
  "favoritos.alert.errorAddToFavorites": "Error al añadir favorito",
  "favoritos.alert.errorDeleteToFavorites": "Error al eliminar favorito",
  "Favorites.Wellcome": `<h3>Bienvenido a la sección de tus favoritos.</h3><p>Actualmente, no tienes elementos en tu lista de favoritos. Para agregar tus visualizaciones preferidas a esta sección, haz clic en el botón correspondiente en cada objeto, informe o gráfico y selecciona la opción "Agregar a favoritos".</p><p>Puedes eliminar elementos de tu lista de favoritos en cualquier momento haciendo clic en el icono <i className="ri-delete-bin-line"></i></p>`,
  "visualizaciones.visualizaciones": "Visualizaciones",
  "visualizaciones.modo.objeto": "Modo vista Objeto",
  "visualizaciones.modo.lista": "Modo vista Lista",
  "visualizaciones.fechaCreacion": "Fecha creación",
  "visualizaciones.fechaModificacion": "Fecha modificación",
  'visualizaciones.appname': "Sección",
  'visualizaciones.usuario': "Usuario",
  "visualizaciones.publicarvisualizacion": "Hacer público la visualización.",
  "visualizaciones.despublicarvisualizacion": "Hacer privado la visualización",
  "visualizaciones.vervisualizacion": "Ver visualización",
  "visualizaciones.modal.eliminarVisualizacion": "Se eliminará el objeto.",
  "visualizaciones.modal.accionnoback": "Esta acción no se puede deshacer. ¿Desea continuar?",
  "visualizaciones.acciones.eliminadovisualizacion": "Se ha eliminado la visualización",
  "visualizaciones.noresultados": "Aún no tiene ninguna visualización personalizada.",
  "visualizaciones.publicOk": "La visualización se ha publicado correctamente.",
  "visualizaciones.publicKo": "La visualización no se ha publicado correctamente.",
  "visualizaciones.unpublicOk": "La visualización se ha despublicado correctamente.",
  "visualizaciones.unpublicKo": "La visualización no se ha despublicado correctamente.",
  "visualizaciones.placeholder.buscarvisualizaciones": "Buscar visualizaciones...",
  "GlobalSelections.AppDimensions": "Dimensiones de la app",
  "GlobalSelections.CurrentSelections": "Selecciones",
  "GlobalSelections.CurrentSelections.Default": "Selecciones (en estado predeterminado)",
  "GlobalSelections.DimensionsWarning": "Únicamente se muestran las dimensiones presentes en los elementos maestros",
  "GlobalSelections.FilterDimensions": "Buscar dimensiones",
  "GlobalSelections.FilterDimensionsAndFields": "Buscar dimensiones y campos",
  "GlobalSelections.HideFields": "Ocultar campos",
  "GlobalSelections.NoMatchesForSearch": "No hay resultados.",
  "GlobalSelections.NoSelections": "No se ha aplicado ninguna selección",
  "GlobalSelections.NoSelectionsBody": "Aplique selecciones desde los campos a continuación para explorar las asociaciones en sus datos. Las selecciones que haga en la hoja también se mostrarán aquí.",
  "GlobalSelections.ShowFields": "Mostrar campos",
  "compare.nameEstadoTxtInicial": 'Estado Inicial',
  "compare.label.estadoInicial": "Devolver gráfico a su estado inicial",
  "compareobject.btn.messageopen": 'Selecciona con que quieres hacer la comparación..',
  "compareobject.btn.sameobject": 'Mismo gráfico',
  "compareobject.btn.listobject": 'Elegir de la lista',
  "compare.btn.newstate": 'Nuevo estado',
  "compare.btn.listastaters": 'Lista estados',
  "compare.btn.exportpdf": 'Exportar a PDF',
  "compare.tooltips.close": 'Cerrar la ventana eliminando los estados creados',
  "compareobject.btn.hideFilterSection": "Ocultar filtros",
  "compareobject.btn.showFilterSection": "Mostrar filtros",
  "compare.label.filtersMensaje": "Aplique selecciones desde los campos a continuación para explorar las asociaciones en sus datos.",
  "compare.tooltips.createsatate": 'Crear un nuevo estado.',
  "compare.tooltips.openliststates": 'Abrir lista de los estados creados',
  "compare.tooltips.sameobject": 'Elegir el gráfico inicial para compararlo consigo mismo',
  "compare.tooltips.listobject": 'Elegir un gráfico de la lista para compararlo',
  "compare.modal.headermodal": 'Crear nuevo estado',
  "compare.modal.labeltitle": 'Título estado',
  "compare.modal.mensajepdf": 'Descargando PDF',
  "compare.acciones.KOState": "Debe introducir el nombre del estado",
  "compare.acciones.CrearState": "Se ha creado el estado",
  "compare.acciones.DeleteState": "Se ha eliminado el estado",
  "compare.acciones.EliminarState": "Se ha eliminado el estado",
  "compare.acciones.Stateexiste": "Ya existe un estado con este nombre. Asigne otro nombre al estado.",
  "compare.acciones.fullsize": "Pantalla completa",
  "compare.acciones.normalsize": "Salir pantalla completa",
  "compare.acciones.vistaColumna": "Vista columna",
  "compare.acciones.vistaRow": "Vista fila",
  "compare.pdf.Objeto_1": "Generando imagen objeto principal",
  "compare.pdf.Objeto_2": "Generando imagen objeto secundario",
  "compare.pdf.selecciones_1": "Generando selecciones objeto principal",
  "compare.pdf.selecciones_2": "Generando selecciones objeto secundario",
  "compare.pdf.imgCoorporativa": "Obteniendo imágen corporativa",
  "compare.pdf.title": "Comparativa de gráficos",
  "compare.pdf.objetoPrincipal": "Gráfica principal",
  "compare.pdf.objetoSecundario": "Gráfica seleccionada",
  "compare.tooltips.estadoInicial": "Devolver gráfico a su estado inicial",
  'compare.tooltips.reloadObject': "Recargar el gráfico",
  "compare.tooltips.exportimagen": "Exportar como imagen",
  "compare.tooltips.exportdatos": "Exportar datos",
  "compare.tooltips.addFilter": "Añadir selección al gráfico",
  "compare.tooltips.verGrafico": "Ver gráfico",
  "compare.tooltips.verDatos": "Ver datos",
  "compare.pdf.selecciones": "Selecciones",
  "compare.pdf.addtitle": "Título PDF",
  "compare.pdf.askForTitle": "Por favor, ingrese un título para su informe.",
  "compare.pdf.txtCaracter": "caracteres",
  "compare.object.error": "Lo sentimos, se ha producido un error inesperado. Por favor, inténtalo de nuevo más tarde. Si el problema persiste, no dudes en ponerte en contacto con nuestro equipo de soporte para obtener ayuda. Disculpa las molestias.",
  "compare.AlternateState.NewStateName": "Nombre del nuevo estado",
  "sheets.modal.title": "Información Hoja Personalizada",
  "sheets.modal.SI": "SI",
  "sheets.modal.NO": "NO",
  "sheets.menu.sheet": "Hojas personalizadas",
  "sheets.openapp": "Abrir aplicación",
  "sheets.infoSheet": "Información",
  "sheets.closeInfoSheet": "Cerrar Información",
  "order.menu.nombreHoja": "Nombre de Hoja",
  "order.menu.publicado": "Publicado",
  "order.menu.aprovado": "Aprobado",
  "order.menu.fechacreacion": "Fecha de creación",
  "order.menu.fechapublicacion": "Hora de publicación",
  "order.menu.fechamodificacion": "Fecha de modificación",
  "order.menu.propietario": "Propietario",
  "equalizer.label.datos": 'Datos',
  "equalizer.label.ordenar": 'Ordenar',
  "equalizer.label.presentacion": 'Presentación',
  "equalizer.label.colores": 'Colores y Leyendas',
  "equalizer.label.cabecerasyetiquetas": 'Cabeceras y etiquetas',
  "equalizer.label.cabecera": 'Cabeceras',
  "equalizer.label.superponeretiquetas": 'Superponer etiquetas',
  "equalizer.label.etiquetashojas": 'Etiquetas de hojas',
  "equalizer.label.etiquetasvalores": 'Etiquetas de valores',
  "equalizer.label.titulos": 'Títulos',
  "equalizer.label.dimensiones": 'Dimensiones',
  "equalizer.label.medidas": 'Medidas',
  "equalizer.label.campos": 'Campos',
  "equalizer.label.ascendente": 'Ascendente',
  "equalizer.label.descendente": 'Descendente',
  "equalizer.label.valoresextremos": 'Incluir valores extremos',
  "equalizer.label.vertical": 'Vertical',
  "equalizer.label.horizontal": 'Horizontal',
  "equalizer.label.agrupado": 'Agrupado',
  "equalizer.label.apilado": 'Apilado',
  "equalizer.label.valoresperdidos": 'Valores perdidos',
  "equalizer.label.mostrarhuecos": 'Mostrar como huecos',
  "equalizer.label.mostrarconexiones": 'Mostrar como conexiones',
  "equalizer.label.mostrarceros": 'Mostrar como ceros',
  "equalizer.label.mostrarpuntos": 'Mostrar puntos de datos',
  "equalizer.label.tamanioburbuja": 'Tamaño de burbuja',
  "equalizer.label.reolucioncompresion": 'Resolución de compresión',
  "equalizer.label.puntosfluctuacion": 'Puntos de fluctuación',
  "equalizer.label.activado": 'Activado',
  "equalizer.label.desactivado": 'Desactivado',
  "equalizer.label.personalizado": 'Personalizado',
  "equalizer.label.colorunico": 'Color único',
  "equalizer.label.porDimension": 'Por dimensión',
  "equalizer.label.porMedida": 'Por medida',
  "equalizer.label.multicolor": 'Multicolor',
  "equalizer.label.porExpresion": 'Por Expresión',
  "equalizer.label.esquemacolor": 'Esquema de color',
  "equalizer.label.mostrarleyenda": 'Mostrar leyenda',
  "equalizer.label.mostrarleyendaTitulo": 'Mostrar título de leyenda',
  "equalizer.label.mostrartitulo": 'Mostrar títulos',
  "equalizer.label.mostraretiqueta": 'Mostrar etiqueta',
  "equalizer.label.titulo": 'Título',
  "equalizer.label.subtitulo": 'Subtítulo',
  "equalizer.label.piepagina": 'Nota a pie de página',
  "equalizer.label.posicionleyenda": 'Posición de leyenda',
  "equalizer.label.posicion": 'Posición',
  "equalizer.label.automatico": 'Automático',
  "equalizer.label.derecha": 'Derecha',
  "equalizer.label.final": 'Final',
  "equalizer.label.izquierda": 'Izquierda',
  "equalizer.label.principio": 'Principio',
  "equalizer.label.etiquetavalores": 'Etiquetas de valores',
  "equalizer.label.capas": 'Capas',
  "equalizer.label.configuracionmapa": 'Configuraciones de mapa',
  "equalizer.label.idiomamapa": 'Idioma del mapa',
  "equalizer.label.capa.puntos": 'Capa de puntos',
  "equalizer.label.capa.grafico": 'Capa de gráfico',
  "equalizer.label.capa.lineas": 'Capa de lineas',
  "equalizer.label.capa.densidad": 'Capa de densidad',
  "equalizer.label.capa.area": 'Capa de área',
  "equalizer.label.capa.fondo": 'Capa de fondo',
  "equalizer.label.mapabase": 'Mapa base',
  "equalizer.label.prederminado": 'Predeterminado',
  "equalizer.label.palido": 'Pálido',
  "equalizer.label.satelite": 'Satélite',
  "equalizer.label.ninguna": 'Ninguna',
  "equalizer.label.todos": 'Todos',
  "equalizer.label.cuota": 'Cuota',
  "equalizer.label.valores": 'Valores',
  "equalizer.label.ingles": 'Inglés',
  "equalizer.label.local": 'Local',
  "equalizer.label.zoomauto": 'Zoom automático',
  "equalizer.label.mostrarcapa": 'Mostrar capa',
  "equalizer.label.rangoburbuja": 'Rango de tamaño de la burbuja',
  "equalizer.label.rangotriangulo": 'Tamaño de triángulo',
  "equalizer.label.rangocuadrado": 'Tamaño de cuadrado',
  "equalizer.label.rangopentagono": 'Tamaño de pentágono',
  "equalizer.label.rangohexagono": 'Tamaño de hexágono',
  "equalizer.label.rangotarta": 'Tamaño del gráfico de tarta',
  "equalizer.label.rangolinea": 'Ancho de línea',
  "equalizer.label.radioinfluencia": 'Radio de influencia',
  "equalizer.label.alto": 'Alto',
  "equalizer.label.ancho": 'Ancho',
  "equalizer.label.navegacion": 'Navegación',
  "equalizer.label.etiquetas": 'Etiquetas',
  "equalizer.label.linea": 'Linea',
  "equalizer.label.area": 'Área',
  "equalizer.label.escalalogaritmica": 'Escala logarítmica',
  "equalizer.label.tarta": 'Tarta',
  "equalizer.label.donut": 'Donut',
  "equalizer.label.colorespersistentes": 'Colores persistentes',
  "equalizer.label.expandirtodo": 'Expandir todo',
  "equalizer.label.contraertodo": 'Contraer todo',
  "equalizer.label.tablatotales": 'Totales',
  "equalizer.label.desplazamiento": 'Desplazamiento',
  "equalizer.label.inmovilizarColumna": 'Inmovilizar primera columna',
  "equalizer.label.desHorizontal": 'Desplazamiento horizontal',
  "equalizer.label.ajustesTexto": 'Ajustes de texto multilinea',
  "equalizer.label.textoCabecera": 'Ajustar texto de cabecera',
  "equalizer.label.textoCelda": 'Ajustar texto de celda',
  "equalizer.label.filtros": "Filtros",
  "equalizer.label.stylesline": "Estilos de línea",
  "equalizer.btn.guardar": 'Guardar',
  "equalizer.btn.aplicar": 'Aplicar',
  "equalizer.btn.cancelar": 'Cancelar',
  "equalizer.btn.cerrar": 'Cerrar',
  "equalizer.btn.descartar": 'Descartar',
  "equalizer.title.mover": 'Mover',
  "equalizer.title.ascendente": 'Ascendente',
  "equalizer.title.descendente": 'Descendente',
  "equalizer.title.vertical": 'Vertical',
  "equalizer.title.horizontal": 'Horizontal',
  "equalizer.modal.atencion": 'Atención',
  "equalizer.modal.aviso": 'No se han guardado los cambios.',
  "equalizer.modal.avisoClose": 'Descartar cambios.',
  "equalizer.modal.cambios": '¿Aplicar los cambios?',
  "equalizer.modal.cambiosexplicacion": 'Todos los cambios se aplicarán a las propiedades del objeto.',
  "equalizer.modal.errormensaje": 'La selección ha creado una inconsistencia.',
  "equalizer.language.spaniol": 'Español',
  "equalizer.language.ingles": 'Inglés',
  "equalizer.language.frances": 'Francés',
  "equalizer.geo.properties.showDebugInfo": "Información del depurador",
  "Object.PieChart": "Gráfico de tarta",
  "Object.BarChart": "Gráfico de barras",

  "treepermissions.titles.roles": "Roles",
  "treepermissions.titles.perfiles": "Perfiles",
  "treepermissions.titles.groups": "Grupos",
  "treepermissions.titles.users": "Usuarios",
  "treepermissions.titles.functionality": "Opciones",
  "treepermissions.titles.identification": "Información personal",
  "treepermissions.titles.rulesapplied": "Reglas aplicadas",
  "treepermissions.actions.selectall": "seleccionar todos",
  "treepermissions.actions.newuser": "nuevo usuario",
  "treepermissions.actions.newgroup": "nuevo grupo",
  "treepermissions.actions.newrole": "nuevo rol",
  "treepermissions.actions.newprofile": "nuevo perfil",
  "treepermissions.placeholder.search": "buscar...",
  "treepermissions.buttons.new": "Nuevo",
  "treepermissions.buttons.new.role": "Rol",
  "treepermissions.buttons.new.profile": "Perfil",
  "treepermissions.buttons.new.group": "Grupo",
  "treepermissions.buttons.new.user": "Usuario",
  "treepermissions.buttons.assign": "Asignar",
  "treepermissions.buttons.delete": "Eliminar",
  "treepermissions.buttons.rules": "Reglas",
  "treepermissions.buttons.save": "Guardar",
  "treepermissions.buttons.add": "Añadir",
  "treepermissions.buttons.accept": "Aceptar",
  "treepermissions.buttons.cancel": "Cancelar",
  "treepermissions.buttons.close": "Cerrar",
  "treepermissions.buttons.replace": "Reemplazar",
  "treepermissions.buttons.edit": "Editar",
  "treepermissions.buttons.expandall": "Expandir todo",
  "treepermissions.buttons.collapseall": "Contraer todo",
  "treepermissions.rules.empty": "No hay reglas para mostrar",
  "treepermissions.legend.allowed": "Permitir",
  "treepermissions.legend.blocked": "Bloquear",
  "treepermissions.legend.indeterminate": "Sin determinar",
  "treepermissions.legend.blank": "Vacío",
  "treepermissions.modals.userform.user": "Usuario",
  "treepermissions.modals.userform.firstname": "Nombre",
  "treepermissions.modals.userform.lastname": "Apellidos",
  "treepermissions.modals.userform.domain": "Dominio",
  "treepermissions.modals.userform.gender": "Género",
  "treepermissions.modals.userform.email": "e-Mail",
  "treepermissions.modals.userform.address": "Dirección",
  "treepermissions.modals.userform.phone": "Teléfono",
  "treepermissions.modals.userform.role": "Rol",
  "treepermissions.modals.userform.birthday": "Cumpleaños",
  "treepermissions.modals.delete.title": "¿Quieres eliminar lo seleccionado?",
  "treepermissions.modals.assign.title": "Asignar grupos",
  "treepermissions.modals.assign.body": "¿Desea añadir o reemplazar los grupos seleccionados?",
  "treepermissions.modals.assign.role.title": "Asignar rol",
  "treepermissions.modals.assign.role.body": "¿Desea reemplazar el rol seleccionado?",
  "treepermissions.modals.assign.profile.title": "Asignar perfil",
  "treepermissions.modals.assign.profile.body": "¿Desea reemplazar el perfil seleccionado?",
  "treepermissions.modals.delete.rule.title": "Eliminar la regla",
  "treepermissions.modals.delete.rule.body": "¿Quieres eliminar la regla '{{rule}}'?",
  "treepermissions.modals.save.label": "Opciones de guardado",
  "treepermissions.modals.save.title": "¿Qué quieres guardar?",
  "treepermissions.modals.save.section1": "Opciones",
  "treepermissions.modals.save.section1.opt1": "Añadir los permisos a los usuarios",
  "treepermissions.modals.save.section1.opt1small": "Se añadirán los permisos a los usuarios sin eliminar los ya creados.",
  "treepermissions.modals.save.section1.opt2": "Reemplazar permisos seleccionados",
  "treepermissions.modals.save.section1.opt2small": "Los permisos antiguos serán borrados y reemplazados por los seleccionados.",
  "treepermissions.modals.save.section1.opt3": "Crear una regla",
  "treepermissions.modals.save.section1.opt3small": "Se creará una regla que aplique los permisos a la selección. Es necesario haber seleccionado un rol o un grupo.",
  "treepermissions.modals.save.section2": "Selecciones",
  "treepermissions.modals.save.section2.opt1": "Solo se aplica a usuarios seleccionados",
  "treepermissions.modals.save.section2.opt2": "Se aplica a usuarios seleccionados y relacionados",
  "treepermissions.modals.save.section3": "Nombre de la regla",
  "treepermissions.modals.save.section3.replace": "La regla ya existe, ¿quieres reemplazarla?",
  "treepermissions.modals.save.section3.required": "Es necesario un nombre de regla",
  "treepermissions.modals.save.section3.placeholder": "Escribe el nombre de la regla...",
  "treepermissions.toast.permissionsload": '¡Permisos cargados correctamente!',
  "treepermissions.toast.roleupdate": "Rol actualizado con éxito",
  "treepermissions.toast.rolecreate": "Rol creado con éxito",
  "treepermissions.toast.profileupdate": "Perfil actualizado con éxito",
  "treepermissions.toast.profilecreate": "Perfil creado con éxito",
  "treepermissions.toast.groupupdate": "Grupo actualizado con éxito",
  "treepermissions.toast.groupcreate": "Grupo creado con éxito",
  "treepermissions.toast.roledelete": "El rol '{{role}}' se eliminó correctamente",
  "treepermissions.toast.profiledelete": "El perfil '{{role}}' se eliminó correctamente",
  "treepermissions.toast.groupdelete": "El grupo '{{group}}' se eliminó correctamente",
  "treepermissions.toast.userdelete": "El usuario '{{user}}' se eliminó correctamente",
  "treepermissions.toast.deleteselerror": "Es necesario seleccionar al menos un usuario, un rol o un grupo",
  "treepermissions.toast.deleteselerrorperfil": "Es necesario seleccionar al menos un usuario, un perfil o un grupo",
  "treepermissions.toast.assignselerror01": "Es necesario seleccionar al menos un usuario y un rol o grupo",
  "treepermissions.toast.assignselerror01perfil": "Es necesario seleccionar al menos un usuario y un perfil o grupo",
  "treepermissions.toast.assignselerror02": "Solo se permite un rol por usuario",
  "treepermissions.toast.assignselerror02perfil": "Solo se permite un perfil por usuario",
  "treepermissions.toast.assignselsuccess01": "El grupo y los roles se han agregado correctamente",
  "treepermissions.toast.assignselsuccess01perfil": "El grupo y los perfiles se han agregado correctamente",
  "treepermissions.toast.assignselsuccess02": "Grupo y roles han sido reemplazados con éxito",
  "treepermissions.toast.assignselsuccess02perfil": "Grupo y perfiles han sido reemplazados con éxito",
  "treepermissions.toast.assignselsuccess03": "Rol ha sido reemplazado con éxito",
  "treepermissions.toast.assignselsuccess03perfil": "Perfil ha sido reemplazado con éxito",
  "treepermissions.toast.savedialogsuccesscreated": "Usuario creado con éxito",
  "treepermissions.toast.savedialogsuccessupdated": "Usuario actualizado con éxito",
  "treepermissions.toast.savedialogerror": "Se debe seleccionar al menos una funcionalidad",
  "treepermissions.toast.rulecreate": "La regla '{{rule}}' se creó correctamente",
  "treepermissions.toast.permissionscreate": "Permisos creados exitosamente",
  "treepermissions.toast.ruledelete": "La regla '{{rule}}' se eliminó correctamente",
  "treepermissions.toast.sequelizeerrorforeignkey": "Error, se hace referencia al registro en otra tabla",
  "views.label.preferencias" : "Preferencias",
  "views.label.marcadores": "Marcadores",
  "views.label.glosario": "Glosario",
  "views.label.filtros": "Filtros",
  "views.label.temas": "Temas",
  "views.label.opciones": "Opciones",
  "views.label.videos": "Vídeos",
  "views.label.loadvideos" : "Buscando videos de ayuda....",
  "views.label.novideos" : "Actualmente no hay videos de ayuda subidos.",
  "views.search.Placeholder": "Buscar",
  contextMenu: {
    "label.volver": "Atrás",
    "label.PantallaCompleta": "Pantalla completa",
    "label.SalirPantallaCompleta": "Salir del modo de pantalla completa",
    "label.verGrafico": "Ver gráfico",
    "label.verDatos": "Ver datos",
    "label.descargarComo": "Descargar como",
    "label.exportImagen": "Imagen",
    "label.exportPdf": "PDF",
    "label.exportDatos": "Datos",
    "label.softPatches": 'Volver estado inicial',
    "label.expand": "Expandir/Contraer",
    "label.expandirtodo": 'Expandir todo',
    "label.contraertodo": 'Contraer todo',
    "label.copyToClipboard": 'Copiar valor de celda',
    "label.compararObjetos": 'Comparativa',
    "label.menuexploracion": 'Abrir menú de exploración',
    "label.compartir": 'Compartir',

  },
  common: {
    "label.esperar": "Por favor espere.",
    "Common.Aceptar": "Aceptar",
    "Common.Cancel": "Cancelar",
    "Common.Eliminar": "Eliminar",
    "Common.Atencion": "Atención",
    "Common.Buscar": "Buscar",
    "Common.Cerrar": "Cerrar",
    "Common.Copy": "Copiar",
    "ObjectNotFound": "No se ha podido cargar el objeto.</br>Consulte con el proveedor.",
    "Common.LastReloadTime": "Última actualización",
    "Common.logoutconfirm" : "¿Está seguro de cerrar la sesión?",
    inicio: "Inicio",
    about: "About",
    contact: "Contact",
    home: "Home"
  },
  menu: {
    inicio: "Inicio",
    ventas: "Ventas",
    financiero: "Financiero",
    favoritos: "Favoritos",
    visualizaciones: "Visualizaciones",
    permisos: "Permisos",
    analisis: "Análisis",
    distribucion: "Distribución",
    evolucionIndicadores: "Evolución Indicadores",
    indicadores: "Indicadores",
    resumen: "Resumen",
    sheet: "Hojas personalizadas",
  },
  sheetCreation: {
    "title": "Crear una nueva hoja",
    "intro": "Las hojas personalizadas se crean desde la aplicación Qlik Sense. Puede abrir la aplicación Qlik Sense conectada a este módulo pulsando el botón",
    "buttonText": "ABRIR_APLICACION",
    "instructions": "Una vez haya abierto la aplicación, haga lo siguiente:",
    "step1": "Desde la vista general de app, haga clic en el icono para ver las hojas.",
    "step2": "Haga clic en el icono para crear una nueva hoja o en Crear nueva hoja.",
    "step3": {
      "title": "Asigne un título a la hoja con la siguiente nomenclatura:",
      "part1": "Comience con el prefijo definido",
      "part2": "Añada el módulo al que pertenece la hoja, terminando con un punto. Los nombres de los módulos son (cada uno es una aplicación distinta):",
      "part3": "Termine el título de la hoja con el nombre por el que desea que se muestre la hoja personalizada."
    },
    "step4": "Añada una descripción.",
    "step5": "Haga clic fuera del área de texto para guardar el título y la descripción.",
    "example": "Ejemplo :",
    "createdSheet": "Se ha creado una nueva hoja. Sus hojas son privadas hasta que las haga públicas.",
    "makePublicInfo": "Para más información, vea <a href='https://help.qlik.com/es-ES/cloud-services/Subsystems/Hub/Content/Sense_Hub/Share/make-public-or-private.htm' target='_blank'>Otorgar acceso a hojas, marcadores e historias.</a>",
    "refreshInfo": "Para poder visualizar la nueva hoja creada deberá actualizar la página en el navegador.",
    "buttonOpenApp": "Abrir aplicación"
  }
};
export default translationES;
